### ISSUE TITLE
Apply Best practices for building containers in generated containers in the project 

### ISSUE THREAD

**Issue by daniel-cit** [GoogleCloudPlatform/terraform-google-secured-data-warehouse#85]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description

Apply Best practices for building containers in generated containers in the project

### References

* https://cloud.google.com/architecture/best-practices-for-building-containers
* https://cloud.google.com/container-registry/docs/container-analysis

**Comment by renato-rudnicki** [comment]
Package a single app per container - ok

Properly handle PID 1, signal handling, and zombie processes - ok

Optimize for the Docker build cache - ok

Remove unnecessary tools - ok

Build the smallest image possible - ok

Scan images for vulnerabilities - ok 

Properly tag your images - ok

File system content - ok
By default, Docker runs the container as root user. It shouldn't be a problem since the container remains alive during the build time only. After that, the container is destroyed.
